### ISSUE TITLE
fatal error: 'clang/Analysis/AnalysisContext.h'

### ISSUE THREAD

**Issue by elijah-z142** [facebook/facebook-clang-plugins#11]
I built clang using clang/setup.sh and then tried "make". In "analyzer/ObjCARCQualifierChecker.cpp" there is an import of "clang/Analysis/AnalysisContext.h". This file is simply not present in "clang/install/include/clang/Analysis". The folder does exist, but the file is not present there.

I've tried this on both Fedora and MacOS Sierra, but the file is not present in the .tar.gz file either, so its not a platform issue, just a missing file or wrong clang version in the .tar.gz.

"make" output:

> [elijah@localhost facebook-clang-plugins]$ make
> make -C analyzer all
> make[1]: Entering directory '/home/elijah/RuntimeConverter/other/facebook-clang-plugins/analyzer'
> clang++ -std=c++14 -fPIC -g -I../clang/install/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -fno-common -Woverloaded-virtual -Wcast-qual -fno-strict-aliasing -pedantic -Wno-long-long -Wall -W -Wno-unused-parameter -Wwrite-strings -Wno-uninitialized  -Wno-missing-field-initializers -Wno-vla-extension -Wno-c99-extensions -O3 -DNDEBUG -c ObjCARCQualifierChecker.cpp -o build/ObjCARCQualifierChecker.o
> ObjCARCQualifierChecker.cpp:19:10: fatal error: 'clang/Analysis/AnalysisContext.h' file not found
> #include "clang/Analysis/AnalysisContext.h"

**Comment by elijah-z142** [comment]
"make libtooling" does work though, which is want I wanted anyways.

**Comment by cyw3** [comment]
I also encounter this problem.
How to solve it?

**Comment by jvillard** [comment]
@cyw3 what do you want to do?
