### ISSUE TITLE
"clang_ast.atd" does not work with adtj for Java generation

### ISSUE THREAD

**Issue by elijah-z142** [facebook/facebook-clang-plugins#14]
This is does not seem to be an issue with "facebook-clang-plugins" itself, but "clang_ast.atd" does not work with adtj for Java generation.

I've opened a ticket with ATD (https://github.com/mjambon/atd/issues/179). I am using atdj 2.0.0.

Is there a workaround for Java generation such as using an older version of clang_ast.atd? Does Facebook only use atd with ocaml?

Command used: `atdj clang_ast.atd`

[clang_ast.atd.txt](https://github.com/facebook/facebook-clang-plugins/files/2656013/clang_ast.atd.txt)

**Comment by jvillard** [comment]
Closing this issue as the issue opened on the atd repo is more actionable.
