### ISSUE TITLE
Package in findlib / OPAM?

### ISSUE THREAD

**Issue by Isweet** [facebook/facebook-clang-plugins#15]
Hey there,

We would like to use this package in our OCaml project. We are happy to package it up as an OPAM package, but need advice on creating a META file. Can the Makefile do this? I usually rely on the build system (e.g. Oasis, Dune, etc.) to do this for me.

Any tips?

**Comment by jvillard** [comment]
The Makefile is quite custom so I think a handwritten META file makes sense for this project.

What parts of this project are you interested in having in the opam package? That will probably require publishing the clang installation and the clang plugin in this repo alongside the OCaml part.

Side note: As far as I know the only user of this project for now is [infer](https://github.com/facebook/infer/) and it has this project directly as a git submodule. Not saying this is necessarily what you'd want though.

**Comment by XVilka** [comment]
@Isweet did you manage to package it?

**Comment by jvillard** [comment]
Please re-open for more updates or further questions.
