### ISSUE TITLE
Unbound record field sl_file

### ISSUE THREAD

**Issue by calebh** [facebook/facebook-clang-plugins#17]
Running `make -C clang-ocaml test` results in the following error when compiling the file `yojson_utils_test.ml`:

```
make -C clang-ocaml test
make: Entering directory '/home/caleb/Documents/deepdecompilerproject/facebook-clang-plugins/clang-ocaml'
ocamldep -native -I build clang_ast_main_test.ml clang_ast_yojson_validator.ml clang_ast_visit.ml utils_test.ml yojson_utils.ml clang_ast_types.ml process.ml clang_ast_converter.ml clang_ast_named_decl_printer.ml clang_ast_proj_test.ml utils.ml yojson_utils_test.ml process_test.ml clang_ast_main.ml yojson_utils.mli process.mli utils.mli build/clang_ast_t.mli build/clang_ast_t.ml build/clang_ast_j.mli build/clang_ast_j.ml build/clang_ast_v.mli build/clang_ast_v.ml build/clang_ast_proj.mli build/clang_ast_proj.ml | sed -e 's/\([a-zA-Z0-9_]*\.cm.\)/build\/\1/g' | sed -e 's/build\/build\//build\//g' > .depend
ocamlfind ocamlopt -package unix,atdgen,atdgen-runtime,camlzip -I build -safe-string -o build/yojson_utils_test.cmx -c yojson_utils_test.ml
File "yojson_utils_test.ml", line 11, characters 12-19:
Error: Unbound record field sl_file
make: *** [Makefile:40: build/yojson_utils_test.cmx] Error 2
make: Leaving directory '/home/caleb/Documents/deepdecompilerproject/facebook-clang-plugins/clang-ocaml'
```

Attempting to add a qualifier to the `sl_file` field does not resolve the issue (ie, prepending `Clang_ast_t.`) does not resolve the issue (same error)

I was able to compile the `.depend` makefile target (not the `depend` target as the readme suggests), as well as the Clang compiler and libtooling (and all the libtooling tests passed).

System:
Ubuntu 19.10
OCaml version 4.05.0
camlzip 1.10
yojson 1.7.0
atd 2.0.0
atdgen 2.0.0

**Comment by jvillard** [comment]
Hi @calebh, sorry I missed your issue and didn't reply sooner. I cannot reproduce the issue locally. Please re-open if this is still happening with the current version of the plugins and I will investigate.
