### ISSUE TITLE
Building the plugin

### ISSUE THREAD

**Issue by mkruber** [facebook/facebook-clang-plugins#8]
Hi, 

I am trying to follow the instructions in the README. While ./clang/setup.sh has been successful, I am unable to do a make test subsequently (CLANG_PREFIX points to the correct install directory within the repo). I get the following on a `make test`:  

`/Applications/Xcode.9.2.0.9C40b.app/Contents/Developer/usr/bin/make -C analyzer all
make[1]: *** No rule to make target `build/PluginMain.o', needed by `build/FacebookAnalyzerPlugin.dylib'.  Stop.
make: *** [all] Error 2`

What needs to be done? I tried a cmake on the analyzer directory which doesn't help either. 

Thanks,
M. 

PS: Also, is there a mailing list to ask questions regarding the plugins?

**Comment by mkruber** [comment]
1) CLANG_PREFIX should not be set 
2) One of the included header files needs to be commented out

**Comment by jvillard** [comment]
Thanks for posting the solution to your question :) What did you need to comment out?

Re: PS: there is no mailing list, feel free to open issues here to ask more questions.

**Comment by mkruber** [comment]
I commented out `#include "clang/Analysis/AnalysisContext.h"` in `analyzer/ObjCARCQualifierChecker.cpp`
